In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [30]:
dir(cancer)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [31]:
x = cancer.data
y = cancer.target
print(x.shape)
print(y.shape)

(569, 30)
(569,)


In [32]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(x)

In [33]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1004)

In [34]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(455, 30)
(114, 30)
(455,)
(114,)


In [35]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)

y_pred = knn.predict(x_test)
scores = metrics.accuracy_score(y_test,y_pred)
confusion_matrix(y_test,y_pred)

array([[44,  7],
       [ 3, 60]])

In [36]:
key_value = {}
for i in range(1, 11):
  knn = KNeighborsClassifier(i)
  knn.fit(x_train,y_train)
  y_pred = knn.predict(x_test)
  acc = metrics.accuracy_score(y_test,y_pred)
  conf_mat = confusion_matrix(y_test, y_pred)

  print("k 값 : ",i)
  print("정확도 : ", acc)
  print("Confusion Matrix : \n", conf_mat)
  print()
  key_value[i]=acc


k 값 :  1
정확도 :  0.8947368421052632
Confusion Matrix : 
 [[43  8]
 [ 4 59]]

k 값 :  2
정확도 :  0.8771929824561403
Confusion Matrix : 
 [[45  6]
 [ 8 55]]

k 값 :  3
정확도 :  0.9122807017543859
Confusion Matrix : 
 [[44  7]
 [ 3 60]]

k 값 :  4
정확도 :  0.9122807017543859
Confusion Matrix : 
 [[45  6]
 [ 4 59]]

k 값 :  5
정확도 :  0.9122807017543859
Confusion Matrix : 
 [[44  7]
 [ 3 60]]

k 값 :  6
정확도 :  0.9035087719298246
Confusion Matrix : 
 [[45  6]
 [ 5 58]]

k 값 :  7
정확도 :  0.9122807017543859
Confusion Matrix : 
 [[44  7]
 [ 3 60]]

k 값 :  8
정확도 :  0.9035087719298246
Confusion Matrix : 
 [[44  7]
 [ 4 59]]

k 값 :  9
정확도 :  0.8947368421052632
Confusion Matrix : 
 [[43  8]
 [ 4 59]]

k 값 :  10
정확도 :  0.8947368421052632
Confusion Matrix : 
 [[43  8]
 [ 4 59]]



In [37]:
print(key_value)

{1: 0.8947368421052632, 2: 0.8771929824561403, 3: 0.9122807017543859, 4: 0.9122807017543859, 5: 0.9122807017543859, 6: 0.9035087719298246, 7: 0.9122807017543859, 8: 0.9035087719298246, 9: 0.8947368421052632, 10: 0.8947368421052632}


In [38]:
max(key_value, key=key_value.get)
[k for k,v in key_value.items() if max(key_value.values()) == v ]

[3, 4, 5, 7]